spring.application.name=dataprev
spring.datasource.url=jdbc:h2:file:./database/paranabanco_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Habilitar o console do H2 para visualiza��o (acess�vel em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
# Spring Batch
# Inicializa o schema do batch no startup
spring.batch.jdbc.initialize-schema=always
# Nunca rodar jobs no startup, faremos isso manualmente via um Runner
spring.batch.job.enabled=false
# Instru��o para o Hibernate criar ou atualizar o schema (tabelas) do banco
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.tool.schema=DEBUG
# Log detalhado das opera��es SQL
logging.level.org.hibernate.SQL=DEBUG
# For�a a execu��o dos scripts SQL (schema.sql, data.sql) sempre.
spring.sql.init.mode=always
# Garante que a cria��o das tabelas pelo Hibernate (ddl-auto) rode ANTES do data.sql
spring.jpa.defer-datasource-initialization=true

leitura.arquivo.caminho=classpath:HMLCES18.B254.D0000001
