package br.com.paranabanco.dataprev.enumeration;

public enum EspecieBeneficio {
    APOSENTADORIA_POR_IDADE, // 41
    APOSENTADORIA_POR_INVALIDEZ_PREVIDENCIARIO, // 32
    PENSAO_POR_MORTE, // 21
    AUXLIO_DOENCA_PREVIDENCIARIO, // 31
    AMPARO_SOCIAL_AO_IDOSO, // 88
    APOSENTADORIA_ESPECIAL, // 46
    APOSENTADORIA_POR_TEMPO_DE_CONTRIBUICAO // 42
}
